# Generated by Django 4.0.5 on 2022-10-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('database', '0001_initial'), ('database', '0002_alter_semester_year'), ('database', '0003_remove_edition_name'), ('database', '0004_alter_edition_date_closed_alter_edition_date_opened'), ('database', '0005_dbaccount_ismoved'), ('database', '0006_remove_studentgroup_group_and_more'), ('database', '0007_alter_group_students'), ('database', '0008_remove_group_teacheredition_group_teacheredition'), ('database', '0009_remove_group_teacheredition_group_teacheredition'), ('database', '0010_remove_group_students_student_groups'), ('database', '0011_remove_student_groups_group_students'), ('database', '0012_alter_dbaccount_editionserver_and_more'), ('database', '0013_alter_course_name_alter_group_students_and_more'), ('database', '0014_alter_group_students'), ('database', '0015_alter_group_students'), ('database', '0016_alter_group_students'), ('database', '0017_alter_server_edition'), ('database', '0018_alter_role_permisssions_alter_role_users'), ('database', '0019_alter_edition_teachers_alter_role_permisssions_and_more'), ('database', '0020_alter_dbaccount_student'), ('database', '0021_alter_dbaccount_student')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('date_opened', models.DateField()),
                ('date_closed', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.course')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('winter', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
                ('port', models.CharField(max_length=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.user')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('database.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.user')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('database.user',),
        ),
        migrations.CreateModel(
            name='TeacherEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.edition')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='EditionServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.CharField(blank=True, default='', max_length=255)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.edition')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.server')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.semester'),
        ),
        migrations.RemoveField(
            model_name='edition',
            name='name',
        ),
        migrations.AlterField(
            model_name='edition',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='date_opened',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='editions', through='database.TeacherEdition', to='database.teacher'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.user')),
                ('student_id', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('database.user',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('day', models.CharField(max_length=30)),
                ('hour', models.CharField(max_length=30)),
                ('room', models.CharField(blank=True, default='', max_length=30)),
                ('teacherEdition', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.teacheredition')),
                ('students', models.ManyToManyField(related_name='groups', to='database.student')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='edition',
            field=models.ManyToManyField(related_name='servers', through='database.EditionServer', to='database.edition'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('permisssions', models.ManyToManyField(blank=True, related_name='roles', to='database.permission')),
                ('users', models.ManyToManyField(blank=True, related_name='roles', to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='DBAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('additional_info', models.CharField(max_length=255)),
                ('editionServer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.editionserver')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_accounts', to='database.student')),
                ('isMovedToExtDB', models.BooleanField(default=False)),
            ],
        ),
    ]
