# Generated by Django 4.0.5 on 2022-10-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_squashed_0021_alter_dbaccount_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='database',
            field=models.CharField(default='db', max_length=30),
        ),
        migrations.AddField(
            model_name='server',
            name='password',
            field=models.CharField(default='root', max_length=30),
        ),
        migrations.AddField(
            model_name='server',
            name='provider',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='server',
            name='user',
            field=models.CharField(default='root', max_length=30),
        ),
    ]
