# Generated by Django 4.0.5 on 2022-11-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_squashed_0029_merge_0002_alter_semester_year_0028_templates_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='active',
        ),
    ]
