# Generated by Django 4.0.5 on 2022-12-19 17:41

import database.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', database.models.UserManager()),
            ],
        ),
    ]
