# Generated by Django 4.0.5 on 2022-10-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_semester_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='name',
        ),
    ]
