# Generated by Django 4.0.5 on 2022-10-17 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_server_database_server_password_server_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dbaccount',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_accounts', to='database.student'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='day',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='hour',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='server',
            name='database',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='server',
            name='provider',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='server',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
