# Generated by Django 4.0.5 on 2022-11-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_course_description_alter_edition_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='database.student'),
        ),
    ]
