# Generated by Django 4.0.5 on 2023-01-24 10:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_dbaccount_editionserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='create_user_template',
            field=models.CharField(blank=True, default='', max_length=1023),
        ),
        migrations.AlterField(
            model_name='server',
            name='delete_user_template',
            field=models.CharField(blank=True, default='', max_length=1023),
        ),
        migrations.AlterField(
            model_name='server',
            name='modify_user_template',
            field=models.CharField(blank=True, default='', max_length=1023),
        ),
    ]
