# Generated by Django 4.0.5 on 2022-12-31 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='role',
            name='users',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
