# Generated by Django 4.0.5 on 2022-10-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_edition_date_closed_alter_edition_date_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbaccount',
            name='isMovedToExtDB',
            field=models.BooleanField(default=False),
        ),
    ]
