# Generated by Django 4.0.5 on 2022-10-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_dbaccount_ismoved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='student',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AddField(
            model_name='edition',
            name='teachers',
            field=models.ManyToManyField(through='database.TeacherEdition', to='database.teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='database.student'),
        ),
        migrations.AddField(
            model_name='role',
            name='permisssions',
            field=models.ManyToManyField(to='database.permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(to='database.user'),
        ),
        migrations.AddField(
            model_name='server',
            name='edition',
            field=models.ManyToManyField(through='database.EditionServer', to='database.edition'),
        ),
        migrations.AlterField(
            model_name='dbaccount',
            name='additional_info',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='editionserver',
            name='additional_info',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.DeleteModel(
            name='StudentGroup',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
