# Generated by Django 4.0.5 on 2022-11-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_group_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='start_year',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('start_year', 'winter'), name='unique_semester'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(check=models.Q(('start_year__gte', 2020), ('start_year__lte', 3000)), name='start_year_between_2020_and_3000'),
        ),
    ]
