# Generated by Django 4.0.5 on 2022-12-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_semester_start_year_semester_unique_semester_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='edition',
            constraint=models.UniqueConstraint(fields=('course', 'semester'), name='unique_edition'),
        ),
    ]
