# Generated by Django 4.0.5 on 2022-12-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_edition_unique_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teacherEdition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.teacheredition'),
        ),
    ]
