# Generated by Django 4.0.5 on 2022-10-06 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_group_teacheredition_group_teacheredition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacherEdition',
        ),
        migrations.AddField(
            model_name='group',
            name='teacherEdition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.teacheredition'),
        ),
    ]
