# Generated by Django 4.0.5 on 2022-12-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_semester_start_year_between_2020_and_3000_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teacheredition',
            constraint=models.UniqueConstraint(fields=('teacher', 'edition'), name='unique_teacher_edition'),
        ),
    ]
