# Generated by Django 4.0.5 on 2022-12-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_group_teacheredition'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='semester',
            name='start_year_between_2020_and_3000',
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(check=models.Q(('start_year__gte', 2000), ('start_year__lte', 3000)), name='start_year_between_2020_and_3000'),
        ),
    ]
