# Generated by Django 4.0.5 on 2022-12-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_teacheredition_unique_teacher_edition'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dbaccount',
            constraint=models.UniqueConstraint(fields=('username', 'editionServer'), name='unique_username_editionserver'),
        ),
    ]
