# Generated by Django 4.0.5 on 2022-10-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_group_teacheredition_group_teacheredition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='database.group'),
        ),
    ]
