# Generated by Django 4.0.5 on 2022-10-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_remove_group_students_student_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='students', to='database.student'),
        ),
    ]
