# Generated by Django 4.0.5 on 2022-12-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_course_name_alter_group_name_alter_major_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('teacherEdition', 'name'), name='unique_group'),
        ),
    ]
