# Generated by Django 4.0.5 on 2022-10-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_remove_student_groups_group_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbaccount',
            name='editionServer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.editionserver'),
        ),
        migrations.AlterField(
            model_name='dbaccount',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.student'),
        ),
    ]
