# Generated by Django 4.0.5 on 2022-10-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_alter_group_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='edition',
            field=models.ManyToManyField(related_name='servers', through='database.EditionServer', to='database.edition'),
        ),
    ]
