# Generated by Django 4.0.5 on 2022-10-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_alter_role_permisssions_alter_role_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='editions', through='database.TeacherEdition', to='database.teacher'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permisssions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='database.permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='roles', to='database.user'),
        ),
    ]
