# Generated by Django 4.0.5 on 2022-10-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_edition_teachers_alter_role_permisssions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbaccount',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbaccounts', to='database.student'),
        ),
    ]
