# Generated by Django 4.0.5 on 2022-10-10 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_alter_dbaccount_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbaccount',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_accounts', to='database.student'),
        ),
    ]
