# Generated by Django 4.0.5 on 2022-10-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_alter_dbaccount_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='database.course'),
        ),
    ]
