# Generated by Django 4.0.5 on 2022-10-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_alter_edition_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionserver',
            name='passwd_template',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='editionserver',
            name='username_template',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
