# Generated by Django 4.0.5 on 2022-10-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_alter_edition_semester'),
        ('database', '0026_templates_entries'),
    ]

    operations = [
    ]
