# Generated by Django 4.0.5 on 2022-10-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_semester_year'),
        ('database', '0028_templates_entries'),
    ]

    operations = [
    ]
